"""Firmware stub generation router.

Generates starter firmware code for the circuit's MCU,
including pin definitions, peripheral init, and main loop stub.
"""

from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel, Field

router = APIRouter()


# ─── Schemas ───


class FirmwareRequest(BaseModel):
    """Request to generate firmware stubs."""

    mcu_part: str = Field(..., description="MCU part number (e.g. STM32F103C8T6)")
    framework: str = Field(
        default="arduino", description="Target framework: arduino, platformio, bare"
    )
    peripherals: list[str] = Field(
        default_factory=list,
        description="Peripherals to initialize: i2c, spi, uart, gpio, adc, pwm",
    )
    pin_map: dict[str, str] = Field(
        default_factory=dict,
        description="Pin label → physical pin mapping (e.g. SDA: PB7)",
    )
    sensors: list[str] = Field(
        default_factory=list,
        description="Connected sensor part numbers for driver includes",
    )


class FirmwareFile(BaseModel):
    filename: str
    language: str
    content: str


class FirmwareResponse(BaseModel):
    files: list[FirmwareFile]
    mcu_part: str
    framework: str
    notes: list[str] = Field(default_factory=list)


# ─── Generator ───


def _generate_arduino(req: FirmwareRequest) -> list[FirmwareFile]:
    """Generate an Arduino/PlatformIO sketch with pin defs and peripheral init."""

    # ── Pin definitions ──
    pin_defs = "\n".join(
        f"#define PIN_{label.upper()}  {pin}" for label, pin in req.pin_map.items()
    )

    # ── Includes ──
    includes = ["#include <Arduino.h>"]
    if "i2c" in req.peripherals:
        includes.append("#include <Wire.h>")
    if "spi" in req.peripherals:
        includes.append("#include <SPI.h>")
    for sensor in req.sensors:
        safe = sensor.replace("-", "_").replace(" ", "_")
        includes.append(f'// #include "{safe}.h"  // TODO: add sensor driver')
    includes_str = "\n".join(includes)

    # ── Setup body ──
    setup_lines = ["  Serial.begin(115200);", f"  // MCU: {req.mcu_part}"]
    if "i2c" in req.peripherals:
        sda = req.pin_map.get("SDA", "SDA")
        scl = req.pin_map.get("SCL", "SCL")
        setup_lines.append(f"  Wire.begin({sda}, {scl});")
    if "spi" in req.peripherals:
        setup_lines.append("  SPI.begin();")
    if "uart" in req.peripherals:
        setup_lines.append("  Serial1.begin(9600);")
    for label, pin in req.pin_map.items():
        upper = label.upper()
        if upper in ("SDA", "SCL", "MOSI", "MISO", "SCK"):
            continue
        setup_lines.append(f"  pinMode(PIN_{upper}, OUTPUT);  // {label}")
    setup_body = "\n".join(setup_lines)

    # ── Loop body ──
    loop_lines = [
        "  // TODO: Read sensors, process data, drive actuators",
        "  delay(100);",
    ]
    loop_body = "\n".join(loop_lines)

    main_content = f"""{includes_str}

// ─── Pin Definitions ───
{pin_defs}

// ─── Setup ───
void setup() {{
{setup_body}
}}

// ─── Main Loop ───
void loop() {{
{loop_body}
}}
"""

    files = [FirmwareFile(filename="main.ino", language="cpp", content=main_content)]

    # ── platformio.ini ──
    if req.framework == "platformio":
        platformio_ini = f"""[env:default]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
monitor_speed = 115200
; MCU: {req.mcu_part}
"""
        files.append(
            FirmwareFile(
                filename="platformio.ini", language="ini", content=platformio_ini
            )
        )

    return files


def _generate_bare(req: FirmwareRequest) -> list[FirmwareFile]:
    """Generate bare-metal C stubs with CMSIS-style setup."""

    pin_defs = "\n".join(
        f"#define PIN_{label.upper()}  {pin}" for label, pin in req.pin_map.items()
    )

    content = f"""/**
 * Bare-metal firmware stub for {req.mcu_part}
 * Generated by ANTIGRAVITY EDA
 */

#include <stdint.h>

// ─── Pin Definitions ───
{pin_defs}

// ─── Peripheral Init ───
void SystemInit(void) {{
    // Clock configuration for {req.mcu_part}
    // TODO: Configure PLL, AHB, APB prescalers
}}

{"void I2C_Init(void) { /* TODO */ }" if "i2c" in req.peripherals else ""}
{"void SPI_Init(void) { /* TODO */ }" if "spi" in req.peripherals else ""}
{"void UART_Init(void) { /* TODO */ }" if "uart" in req.peripherals else ""}
{"void ADC_Init(void) { /* TODO */ }" if "adc" in req.peripherals else ""}
{"void PWM_Init(void) { /* TODO */ }" if "pwm" in req.peripherals else ""}

// ─── Main ───
int main(void) {{
    SystemInit();
{"    I2C_Init();" if "i2c" in req.peripherals else ""}
{"    SPI_Init();" if "spi" in req.peripherals else ""}
{"    UART_Init();" if "uart" in req.peripherals else ""}

    while (1) {{
        // TODO: Main loop
    }}
    return 0;
}}
"""

    return [FirmwareFile(filename="main.c", language="c", content=content)]


# ─── Endpoint ───


@router.post("/generate", response_model=FirmwareResponse)
async def generate_firmware(req: FirmwareRequest):
    """Generate firmware stubs for the circuit's MCU."""

    notes: list[str] = []
    notes.append(f"Target MCU: {req.mcu_part}")
    notes.append(f"Framework: {req.framework}")

    if req.framework in ("arduino", "platformio"):
        files = _generate_arduino(req)
    elif req.framework == "bare":
        files = _generate_bare(req)
    else:
        notes.append(f"Unknown framework '{req.framework}', defaulting to Arduino")
        files = _generate_arduino(req)

    if req.sensors:
        notes.append(
            f"Sensor drivers needed: {', '.join(req.sensors)} — add libraries manually"
        )

    return FirmwareResponse(
        files=files,
        mcu_part=req.mcu_part,
        framework=req.framework,
        notes=notes,
    )
